spring:
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql
  datasource:
    username: ${POSTGRES_USER:bookuser}
    password: ${POSTGRES_PASSWORD:bookuser}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookdb