CREATE TABLE BOOK_AUTHOR
(
    ID VARCHAR(36) PRIMARY KEY,
    BOOK_ID VARCHAR(36) REFERENCES BOOKS(id),
    AUTHOR_ID VARCHAR(36) REFERENCES AUTHORS(id),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_book_author UNIQUE (BOOK_ID, AUTHOR_ID)
)
