CREATE TABLE BOOKS
(
    id         VARCHAR(36) PRIMARY KEY,
    name       VARCHAR(255),
    page_count int,
    version    int,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)
