CREATE TABLE BOOK_AUTHOR
(
    ID UUID PRIMARY KEY,
    BOOK_ID UUID REFERENCES BOOKS(id),
    AUTHOR_ID UUID REFERENCES AUTHORS(id),
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_book_author UNIQUE (BOOK_ID, AUTHOR_ID)
)
