CREATE TABLE AUTHORS
(
    id         UUID PRIMARY KEY,
    name VARCHAR(255),
    version    int,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
)
